Models/Formulario.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

public class Formulario
{
    public int Id { get; set; }
    [Required(ErrorMessage = "Preencha o Nome!")]
    public string? Nome { get; set; }
    public IList<Campo>? Campos { get; set; }
}

Controllers/CadastroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Formularios.Controllers
{
    public class CadastroController : Controller
    {
        private readonly AppDbContext _context;

        public CadastroController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Cadastro
        public async Task<IActionResult> Index()
        {
            return _context.Registros != null ?
                        View(await _context.Registros.ToListAsync()) :
                        Problem("Entity set 'AppDbContext.Registros'  is null.");
        }

        // GET: Cadastro/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Registros == null)
            {
                return NotFound();
            }

            var registroViewModel = await _context.Registros
                .Include(reg => reg.RegInfo)
                .ThenInclude(regInfo => regInfo.Campo)
                .FirstAsync(m => m.Id == id);

            if (registroViewModel == null)
            {
                return NotFound();
            }

            return View(registroViewModel);
        }

        // GET: Cadastro/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Registros == null)
            {
                return NotFound();
            }

            var registroViewModel = await _context.Registros.FindAsync(id);
            if (registroViewModel == null)
            {
                return NotFound();
            }
            return View(registroViewModel);
        }

        // POST: Cadastro/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NomeFormulario")] RegistroViewModel registroViewModel)
        {
            if (id != registroViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(registroViewModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RegistroViewModelExists(registroViewModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(registroViewModel);
        }

        // GET: Cadastro/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Registros == null)
            {
                return NotFound();
            }

            var registroViewModel = await _context.Registros
                .FirstOrDefaultAsync(m => m.Id == id);
            if (registroViewModel == null)
            {
                return NotFound();
            }

            return View(registroViewModel);
        }

        // POST: Cadastro/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Registros == null)
            {
                return Problem("Entity set 'AppDbContext.Registros'  is null.");
            }
            var registroViewModel = await _context.Registros.FindAsync(id);
            if (registroViewModel != null)
            {
                _context.Registros.Remove(registroViewModel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RegistroViewModelExists(int id)
        {
            return (_context.Registros?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/FormularioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NuGet.Packaging;

namespace Formularios.Controllers
{
    public class FormularioController : Controller
    {
        private readonly AppDbContext _context;

        public FormularioController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Formulario
        public async Task<IActionResult> Index()
        {
            return _context.Formularios != null ?
                        View(await _context.Formularios.ToListAsync()) :
                        Problem("Entity set 'AppDbContext.Formularios'  is null.");
        }
        public async Task<IActionResult> VerRegistros(int? id)
        {
            string NomeFormulario = _context.Formularios.Find(id).Nome;
            return _context.Registros != null ?
                View(await _context.Registros
                                .Where(reg => reg.NomeFormulario == NomeFormulario)
                                .ToListAsync()) :
                 Problem("Entity set 'AppDbContext.Registros'  is null.");
        }

        // GET: Formulario/Create
        public IActionResult Create()
        {
            ViewBag.Campos = new SelectList(_context.Campos, "Id", "Nome");
            return View();
        }

        // POST: Formulario/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome")] Formulario formulario)
        {
            var CamposForm = Request.Form["camposForm"];
            int[] CampoIds = CamposForm.ToString().Split(",").Select(Int32.Parse).ToArray();
            var Campos = _context.Campos.Where(campo => CampoIds.Contains(campo.Id)).ToList();
            formulario.Campos = new List<Campo>();
            formulario.Campos.AddRange(Campos);
            if (ModelState.IsValid)
            {
                _context.Add(formulario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Campos = new SelectList(_context.Campos, "Id", "Nome");
            return View(formulario);
        }

        // GET: Formulario/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Formularios == null)
            {
                return NotFound();
            }

            var formulario = await _context.Formularios
            .Include(form => form.Campos)
            .FirstAsync(form => form.Id == id);

            if (formulario == null)
            {
                return NotFound();
            }
            if (formulario.Campos is not null)
                ViewBag.Campos = formulario.Campos.ToList();
            ViewBag.CamposSelect = new SelectList(_context.Campos, "Id", "Nome");

            return View(formulario);
        }

        // POST: Formulario/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome")] Formulario formulario)
        {
            if (id != formulario.Id)
            {
                return NotFound();
            }

            int[] CampoIds = { };

            var CamposForm = Request.Form["camposForm"];
            try
            {
                CampoIds = CamposForm.ToString().Split(",").Select(Int32.Parse).ToArray();
            }
            catch (Exception e) { Console.Write(e.Message); }

            var Campos = new HashSet<Campo>(_context.Campos
            .Where(campo => CampoIds.Contains(campo.Id))
            ).ToHashSet();

            formulario.Campos = new List<Campo>();
            formulario.Campos.AddRange(Campos);

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(formulario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FormularioExists(formulario.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(formulario);
        }

        // GET: Formulario/NovoRegistro/5
        public async Task<IActionResult> NovoRegistro(int? id)
        {
            if (id == null || _context.Formularios == null)
            {
                return NotFound();
            }

            var formulario = await _context.Formularios
                .Include(form => form.Campos)
                .ThenInclude(Campo => Campo.Tipo)
                .FirstAsync(m => m.Id == id);


            if (formulario == null)
            {
                return NotFound();
            }

            return View(formulario);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> NovoRegistro()
        {

            var Campos = Request.Form["campo"];
            var CamposName = Request.Form["campo-name"];
            var NomeFormulario = Request.Form["NomeFormulario"];
            var valores = Campos.ToString().Split(',').ToArray();
            var nomes = CamposName.ToString().Split(',').ToArray();
            var registro = new RegistroViewModel();
            var registrosInfo = new List<RegistroInfoViewModel>();

            foreach (var valor in valores)
            {
                registrosInfo.Add(new RegistroInfoViewModel());
            }

            int i = 0;
            foreach (var registroInfo in registrosInfo)
            {
                registroInfo.Campo = _context.Campos.First(campo => campo.Nome == nomes[i]);
                registroInfo.Dado = valores[i];
                i++;
            }

            registro.NomeFormulario = NomeFormulario;
            registro.RegInfo = new List<RegistroInfoViewModel>();
            registro.RegInfo.AddRange(registrosInfo);

            if (ModelState.IsValid)
            {
                _context.Registros.Add(registro);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Campos = new SelectList(_context.Campos, "Id", "Nome");
            return View(registro);
        }

        // GET: Formulario/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Formularios == null)
            {
                return NotFound();
            }

            var formulario = await _context.Formularios
                .FirstOrDefaultAsync(m => m.Id == id);
            if (formulario == null)
            {
                return NotFound();
            }

            return View(formulario);
        }

        // POST: Formulario/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Formularios == null)
            {
                return Problem("Entity set 'AppDbContext.Formularios'  is null.");
            }
            var formulario = await _context.Formularios.FindAsync(id);
            if (formulario != null)
            {
                _context.Formularios.Remove(formulario);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FormularioExists(int id)
        {
            return (_context.Formularios?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Formulario/Create.cshtml
@model Formulario

@{
    ViewData["Title"] = "Create";
}

<script>
    let addCampo = () => {
        let nomeCampoSelecionado = $("#select-campos option:selected").text()
        let campoValor = $('#select-campos').val()
        let campoNomeForm = `<li class='list-group-item' >${nomeCampoSelecionado}</li>`
        let campoValorForm = `<input type='text' class='hidden' value='${campoValor}' name='camposForm' />`
        if(![...document.getElementsByName("camposForm")].map(campo => campo.value).includes($("#select-campos").val()))
            $('#ul-campos').append(campoNomeForm + campoValorForm)
    }
</script>

<h1>Create</h1>

<h4>Formulario</h4>
<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Campos</label>
                <select asp-items="ViewBag.Campos" class="form-control" id="select-campos" ></select>
                <br>
                <div class="row d-flex justify-content-space-around align-items-center">
                    <div class="form-group col-md-6">
                        <ul id="ul-campos">
                        </ul>
                    </div>
                    <a class="btn btn-primary col-md-6" onclick="addCampo()">Add Campo</a>
                </div>
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
                <br>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Formulario/Delete.cshtml
@model Formulario

@{
    ViewData["Title"] = "Delete";
}

<h1>Deletar</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Formulario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Formulario/Edit.cshtml
@model Formulario

@{
    ViewData["Title"] = "Edit";
}

<script>
    let addCampo = () => {
        let nomeCampoSelecionado = $("#select-campos option:selected").text()
        let campoValor = $('#select-campos').val()
        let campoNomeForm = `<li class='list-group-item' >${nomeCampoSelecionado}</li>`
        let campoValorForm = `<input type='text' class='hidden' value='${campoValor}' name='camposForm' />`
        if(![...document.getElementsByName("camposForm")]
        .map(campo => campo.value).includes($("#select-campos").val()) &&
        ![...document.getElementsByName("view-camposForm")]
        .map(campo => campo.value).includes($("#select-campos").val()))
            $('#ul-campos').append(campoNomeForm + campoValorForm)
    }
</script>

<h1>Editar</h1>

<h4>Formulario</h4>
<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input class="form-control" type="text" asp-for="Nome" />
                <br>
                <select asp-items="ViewBag.CamposSelect" class="form-control" id="select-campos" ></select>
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <div class="row d-flex justify-content-space-around align-items-center">
                    <div class="form-group col-md-6">
                        <ul id="ul-campos">
                            @foreach (var campo in @ViewBag.Campos)
                            {
                                <li class="list-group-item">@campo.Nome</li>
                                <input type="text" class="hidden" value="@campo.Id" name="view-camposForm" />
                            }
                        </ul>
                    </div>
                    <a class="btn btn-primary col-md-6" onclick="addCampo()">Add Campo</a>
                </div>
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Formulario/Index.cshtml
@model IEnumerable<Formulario>

@{
    ViewData["Title"] = "Index";
}

<h1>Formularios</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Deletar</a> |
                <a asp-action="VerRegistros" asp-route-id="@item.Id">Exibir Registros</a> |
                <a asp-action="NovoRegistro" asp-route-id="@item.Id">Novo Registro</a> 
            </td>
        </tr>
}
    </tbody>
</table>

Views/Formulario/NovoRegistro.cshtml
@model Formulario

@{
    ViewData["Title"] = "Details";
}


<div class="row d-flex justify-content-center">
   <form asp-action="NovoRegistro">
        <div class="col-md-6">
            <h1>Formulario de @Html.DisplayFor(model => model.Nome)</h1>
            <input value="@Model?.Nome" name="NomeFormulario" class="hidden">
                @foreach (var campo in Model?.Campos)
                {
                    <label for="form">@campo.Nome</label>
                    @if (campo.Tipo?.Nome.ToLower() == "checkbox")
                    {
                        <input type="text" name="campo-name" value="@campo.Nome" class='hidden' />
                        <input name="campo" type="@campo.Tipo?.Nome.ToLower()" />

                        <br>
                    }
                    else
                    {
                        <input type="text" name="campo-name" value="@campo.Nome" class='hidden' />
                        <input name="campo" name="campo" class="form-control" type="@campo.Tipo?.Nome.ToLower()" />
                    }
                }
        </div>
        <br>
        <div class="form-group">
                <input type="submit" value="Registrar" class="btn btn-primary" />
        </div>
    </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Formulario/VerRegistros.cshtml
@model IEnumerable<RegistroViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                Nome do formulario
            </th>
            <th>
                Id do registro
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NomeFormulario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @* <a asp-action="Edit" asp-route-id="@item.Id" asp-controller="Cadastro">Edit</a> | *@
                <a asp-action="Details" asp-route-id="@item.Id" asp-controller="Cadastro">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id"asp-controller="Cadastro">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>